# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts-as-dag}
  s.version = "1.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthew Leventi", "Robert Schmitt"]
  s.date = %q{2011-02-10}
  s.description = %q{Acts As Dag, short for Acts As Directed Acyclic Graph, is a gem which allows you to represent DAG hierarchy using your ActiveRecord models.}
  s.email = %q{resgraph@cox.net}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/acts-as-dag.rb",
    "lib/dag/dag.rb",
    "test/dag_test.rb"
  ]
  s.homepage = %q{http://github.com/resgraph/acts-as-dag}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{acts-as-dag}
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Acts As DAG Gem}
  s.test_files = [
    "test/dag_test.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

